name: c-lint-and-build
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shenxianpeng/cpp-linter-action@master
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 12
          files-changed-only: false
          tidy-checks: ""
      - name: Linting errors
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ninja
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
      - name: Build with Clang
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
          cd ..
          cmake --build build
        shell: bash
        env:
          CC: clang-12
